eureka:
  client:
    serviceUrl:
      defaultZone: http://123.206.73.78:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: rest-ribbon
    api-b:
      path: /api-b/**
      serviceId: feign